version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.transport.ssl.enabled=false
      - node.name=node-1
      - cluster.name=my-elastic-cluster
      - node.roles=master,data,ingest
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=Azmodeg@n_Database
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - /data/elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elasticnet

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - network.host=0.0.0.0
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=Azmodeg@n_D@t@b@se
    ports:
      - "5601:5601"
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

  minio:
    image: minio/minio:RELEASE.2023-01-25T00-19-54Z
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    volumes:
      - /data/minio-data:/data
    networks:
      - elasticnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-agent-backend
    command: >
      uvicorn app.main:app
      --host ${SERVER_HOST}
      --port ${SERVER_PORT}
      --reload
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - elasticsearch
      - minio
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - MINIO_ENDPOINT=minio:9000
      - MINIO_KEY=${MINIO_KEY}
      - MINIO_SECRET=${MINIO_SECRET}
      - MINIO_BUCKET=${MINIO_BUCKET}
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - TEMPERATURE=${TEMPERATURE}
    networks:
      - elasticnet

networks:
  elasticnet:
    driver: bridge

